### PR TITLE
use pytest

### PR DESCRIPTION
**Pull request by carueda**
Locally, once pytest is installed:

```
pip3 install pytest
```

(already part of requirements.txt), one can then run `pytest tests` or `python -m pytest tests`, the latter being the form used in CI.  Since pytest supports unittest, the initial commit here is just to run the tests via pytest (without changes in the test code).

### CODE REVIEW

**Comment by carueda** [comment]
A 2nd commit with just minimal adjustments to test_utils, which is a good case due to not using setUp, just direct `test_` methods.

Also, I marked this PR as draft because it's initially just intended to demonstrate what the transition to pytest would entail, in particular, I'd like to add some test exercising snaphots, so we can then discuss whether to eventually incorporate or not.

**Comment by carueda** [comment]
A 3rd commit with a new test exercising snapshot based comparison.

**Comment by carueda** [comment]
ok, tests are now passing after doing some adjustments to the snapshot based comparison, in particular, with the use of DataFrame.round() to make the comparison consistent across the various environments (it all started passing for me locally, but not at CI).

Note: had to skip the `test_utils` tests due to unexpected failed asserts. Afaict, except for the reorganized structure, these tests are exactly as in master, so not sure what may be going on.  We will need to revisit these.

**Comment by cparcerisas** [comment]
Yes in test_utils the assert fails because I haven't changed the ground truth results to the correct ones. It will be included under #13

**Comment by carueda** [comment]
I'm manually adjusting things in this PR's branch according to adjustments seen in master ... but will likely re-create the PR given the various (expected) conflicts. If/when deciding that migration to pytest+snapshots is worth pursuing, then we would just need some little coordination to proceed with a merge while avoiding future conflicts.

**Comment by carueda** [comment]
Actually the conflicts were trivial to resolve. This (draft) PR is now up-to-date.

**Comment by carueda** [comment]
Thanks again @cparcerisas for one more great discussion earlier today (PST). Per that conversation, I shall be doing some further adjustments here.

**Review by danellecline — COMMENTED** [review]
These look fine to me, but I'm unfamiliar with PyPam. Maybe better to have @cparcerisas  review too.  Suggest checking not just the formatting of the output, but also the content of the dataframe/csv, e.g. first rows.

**Comment by carueda** [comment]
Thanks @danellecline!

Comparison against content is actually the core objective with snapshot based testing (formatting hasn't been a concern here).

Clea and I already went through this, but I want to have one more look myself at some point (hopefully soon) to then do one more quick coordination and merge.

**Pull request merged**
