### PR TITLE
Feature: Impulsive metrics (kurtosis and energy windowed SPL RMS)

### PR DESCRIPTION
**Pull request by caplinje-NOAA**
Hello,

Finally ready to submit this, the **changes can be summarized** as:

- added kurtosis (in utils, signal, acoustic_file, and units) https://github.com/lifewatch/pypam/issues/106
- added energy windowing method to utils
- added option for energy window computation of rms
- added implusive flag to _event.analyze which calculates all impulsive related metrics
- made a small modification to path handling for testing (was necessary in my IDE to run tests)
- made some improvements to docstrings

**In terms of new math**, the primary things are the kurtosis and energy window calculations.  For kurtosis, I explored the best implementation and documented it [here](https://github.com/caplinje-NOAA/pypam-piledriving/blob/main/examples/kurtosis.ipynb). For the energy window calculation, I followed the standard method from the most often cited reference.  In both cases I added tests which compare against known/expected results for each. Additionally, I built a comprehensive test of all of the new metrics using some example pile driving acoustic data and previously analyzed results. 

**In terms of testing**, everything is passing with the exception of `TestPlots.test_summary_plot` and `TestDataset.test_generate_dataset`. 

Here are the two exceptions from the failed tests:

```
tests\test_dataset.py:66 (TestDataset.test_generate_dataset)
self = <tests.test_dataset.TestDataset testMethod=test_generate_dataset>

>           raise FileNotFoundError('The path %s does not exist. Please choose another one.' % folder_path)
E           FileNotFoundError: The path tests/test_data does not exist. Please choose another one.

..\pypam\acoustic_survey.py:511: FileNotFoundError


================ 2 failed, 50 deselected, 3 warnings in 14.07s ================
FAILED                       [100%]
tests\test_plots.py:78 (TestPlots.test_summary_plot)
self = <tests.test_plots.TestPlots testMethod=test_summary_plot>

        if location is not None:
            if pvlib is None:
>               raise Exception('To use this feature it is necessary to install pvlib ')
E               Exception: To use this feature it is necessary to install pvlib

..\pypam\plots.py:382: Exception
```

**Please let me know if you would like me to split any of this out and submit separate pull requests, as I am realizing this might be a lot for a single pull request.** For example, if you are only interested in including kurtosis, I would definitely understand, as many of my edits specifically relate to performing analysis of anthro impulsive sources. 

Again, it was been really fun to work with and learn this package, thanks!

### CODE REVIEW

**Comment by caplinje-NOAA** [comment]
Small update here: after adding the optional dependencies, all tests pass.

**Comment by caplinje-NOAA** [comment]
Apologies for the messy commit history, and I should note that this branch also contains the bin overlap fix related to https://github.com/lifewatch/pypam/issues/127.  Again, if you want me to more clearly separate out all of these changes, please let me know I can submit pull requests from simpler/cleaner branches.

**Comment by caplinje-NOAA** [comment]
Absolutely no rush on my end - happy to work through this whenever it makes sense. Thanks!

**Review by cparcerisas — APPROVED** [review]

**Comment by caplinje-NOAA** [comment]
Thank you for merging this pull request, I'm seeing that one of my tests are failing in CI.  I believe this is because I'm handling paths in a windows specific way, I'm working on a pull request that should resolve this.

**Pull request merged**
